[package]
name = "rust-crud-api"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
postgres = "0.19.8"
serde = "1.0.204"
serde_derive = "1.0.204"
serde_json = "1.0.122"
