[package]
name = "rust-rest-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-rt = "2.10.0"
actix-web = "4.9.0"
bson = "2.11.0"
dotenv = "0.15.0"
env_logger = "0.11.5"
mongodb = "3.0.1"
serde = "1.0.207"
